#!/bin/bash
cd `dirname $0`
ARGS=$@
sbt -J-Xmx4G \
  -Dorg.slf4j.simpleLogger.defaultLogLevel=info \
  -Dorg.slf4j.simpleLogger.logFile=rehearsal.log \
  --warn \
  "set showSuccess in ThisBuild := false" \
  "run $ARGS"
